### ISSUE TITLE
Not working with dotnet core 2.2

### ISSUE THREAD

**Issue by epmallmann** [Secbyte/dotnet-sonarscanner#11]
Hi.

I'm using this action in another repos and it's great, but they are dotnet core 3.1. 

The problema it is that I have one specific repo that is dotnet core 2.2. I know, we should update it, but it is not possible now. Is it possible to make work with dotnet core 2.2?

The action:
```
name: sonar-qube
on: [pull_request]

jobs:
  scan:
    name: scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2
    
      - name: Scan
        uses: Secbyte/dotnet-sonarscanner@v2.3
        with:
          buildCommand: dotnet build .
          testCommand: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          projectKey: myProject
          sonarHostname: https://sonar.app.movidesk.com
          beginArguments: >
            /d:sonar.cs.opencover.reportsPaths="./myProject/coverage.opencover.xml"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

the result:
```
A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      2.1.23 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      3.1.9 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.2.0&arch=x64&rid=debian.10-x64
. Please check the diagnostic logs for more information.
```

Any chances to make this work? Tks!
