### ISSUE TITLE
Coverage always 0.0%

### ISSUE THREAD

**Issue by Sakamotto** [Secbyte/dotnet-sonarscanner#2]
Hello!!

I'm trying to use dotnet-sonarscanner action to send my code to sonar cloud, but the coverage is not showing correctly on the site.

This is my configuration:

```
on: push
name: Main Workflow
jobs:    
  sonarCloudTrigger:
    name: Sonar Cloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        ref: master
    - uses: Secbyte/dotnet-sonarscanner@v1.2
      with:
        buildCommand: dotnet build .
        testCommand: dotnet test . /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        projectKey: my_p_key
        projectName: my_p_name
        sonarOrganisation: my_org
        beginArguments: /d:sonar.verbose="true" /d:sonar.cs.opencover.reportsPaths="coverage.opencover.xml"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```
What am I doing wrong?
