### ISSUE TITLE
Add Test Parameters?

### ISSUE THREAD

**Issue by equiman** [Secbyte/dotnet-sonarscanner#6]
Could you add test parameters?

`dotnet test Colorify.Tests/Colorify.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../lcov`

It's because I'm coming from Travis CI and the test project needs to be run with some parameters.

```yml
  - dotnet sonarscanner begin /k:"dein:colorify" /n:"Colorify" /v:"2.5.0" /o:"dein" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_KEY" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="lcov.opencover.xml" || true
  - dotnet build Colorify/Colorify.csproj
  - dotnet test Colorify.Tests/Colorify.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../lcov
  - dotnet sonarscanner end /d:sonar.login="$SONAR_KEY" || true
```

**Comment by joshuaduffy** [comment]
This is possible.

`buildCommand` and `testCommand` both allow arguments.

See the readme for an example, it should look something like this:

```
- name: Sonarscanner for dotnet
  uses: Secbyte/dotnet-sonarscanner@v2.2
  with:
    buildCommand: dotnet build Colorify/Colorify.csproj
    testCommand: dotnet test Colorify.Tests/Colorify.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../lcov
    projectKey: a-project-key
    projectName: a-project-name
    sonarOrganisation: an-org
    beginArguments: >
        /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
        /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
